namespace Invoke.Core.Config;

internal static class ThemeSchema
{
    public const string FileName = "theme.schema.json";

    public const string Json =
        """
        {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "title": "Invoke theme",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "$schema": { "type": "string", "description": "Editor schema reference for autocomplete and validation." },
            "name": { "type": "string" },
            "fontFamily": { "type": "string" },
            "fontSize": { "type": "number", "minimum": 8, "maximum": 72 },
            "searchFontSize": { "type": "number", "minimum": 8, "maximum": 96 },
            "resultTitleFontSize": { "type": "number", "minimum": 8, "maximum": 72 },
            "resultSubtitleFontSize": { "type": "number", "minimum": 8, "maximum": 72 },
            "resultTitleFontWeight": { "type": "string" },
            "resultSubtitleFontWeight": { "type": "string" },
            "windowWidth": { "type": "number", "minimum": 240, "maximum": 2560 },
            "windowOpacity": { "type": "number", "minimum": 0.1, "maximum": 1 },
            "cornerRadius": { "type": "number", "minimum": 0, "maximum": 96 },
            "resultCornerRadius": { "type": "number", "minimum": 0, "maximum": 96 },
            "resultLayout": { "type": "string", "enum": ["oneLine", "twoLine"] },
            "showPrompt": { "type": "boolean" },
            "promptPersistent": { "type": "boolean" },
            "promptOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "promptText": { "type": "string" },
            "showStatusPanel": { "type": "boolean" },
            "showIcons": { "type": "boolean" },
            "showSubtitles": { "type": "boolean" },
            "showSelectionAccent": { "type": "boolean" },
            "showItemBorders": { "type": "boolean" },
            "rowHeight": { "type": "number", "minimum": 24, "maximum": 240 },
            "resultGap": { "type": "number", "minimum": 0, "maximum": 96 },
            "spacing": { "type": "number", "minimum": 0, "maximum": 96 },
            "searchHorizontalPadding": { "type": "number", "minimum": 0, "maximum": 96 },
            "searchVerticalPadding": { "type": "number", "minimum": 0, "maximum": 96 },
            "resultHorizontalPadding": { "type": "number", "minimum": 0, "maximum": 96 },
            "resultVerticalPadding": { "type": "number", "minimum": 0, "maximum": 96 },
            "resultTextLeftMargin": { "type": "number", "minimum": 0, "maximum": 96 },
            "resultTextRightMargin": { "type": "number", "minimum": 0, "maximum": 96 },
            "resultSubtitleTopMargin": { "type": "number", "minimum": 0, "maximum": 96 },
            "iconColumnWidth": { "type": "number", "minimum": 0, "maximum": 240 },
            "iconContainerSize": { "type": "number", "minimum": 0, "maximum": 240 },
            "iconSize": { "type": "number", "minimum": 0, "maximum": 240 },
            "fallbackIconSize": { "type": "number", "minimum": 0, "maximum": 240 },
            "fallbackIconCornerRadius": { "type": "number", "minimum": 0, "maximum": 96 },
            "fallbackIconOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "outerShadowMargin": { "type": "number", "minimum": 0, "maximum": 96 },
            "outerShadowOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "outerShadowBlurRadius": { "type": "number", "minimum": 0, "maximum": 256 },
            "outerShadowDepth": { "type": "number", "minimum": 0, "maximum": 256 },
            "outerShadowEffectOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "surfaceBorderThickness": { "type": "number", "minimum": 0, "maximum": 24 },
            "separatorThickness": { "type": "number", "minimum": 0, "maximum": 24 },
            "surfaceShadowBlurRadius": { "type": "number", "minimum": 0, "maximum": 256 },
            "surfaceShadowDepth": { "type": "number", "minimum": 0, "maximum": 256 },
            "surfaceShadowOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "windowTopOffsetMin": { "type": "number", "minimum": 0, "maximum": 1440 },
            "windowTopOffsetRatio": { "type": "number", "minimum": 0, "maximum": 1 },
            "animateLauncherOpen": { "type": "boolean" },
            "animateLauncherClose": { "type": "boolean" },
            "launcherOpenDurationMilliseconds": { "type": "number", "minimum": 0, "maximum": 5000 },
            "launcherCloseDurationMilliseconds": { "type": "number", "minimum": 0, "maximum": 5000 },
            "launcherOpenOffsetY": { "type": "number", "minimum": -240, "maximum": 240 },
            "launcherCloseOffsetY": { "type": "number", "minimum": -240, "maximum": 240 },
            "launcherOpenScale": { "type": "number", "minimum": 0.5, "maximum": 1.5 },
            "launcherCloseScale": { "type": "number", "minimum": 0.5, "maximum": 1.5 },
            "launcherOpenEasing": { "type": "string" },
            "launcherCloseEasing": { "type": "string" },
            "animateResults": { "type": "boolean" },
            "resultsAnimationDurationMilliseconds": { "type": "number", "minimum": 0, "maximum": 5000 },
            "resultsAnimationOffsetY": { "type": "number", "minimum": -240, "maximum": 240 },
            "resultsAnimationStaggerMilliseconds": { "type": "number", "minimum": 0, "maximum": 1000 },
            "resultsAnimationEasing": { "type": "string" },
            "animateSelection": { "type": "boolean" },
            "selectionAnimationDurationMilliseconds": { "type": "number", "minimum": 0, "maximum": 5000 },
            "selectionAnimationOffsetX": { "type": "number", "minimum": -240, "maximum": 240 },
            "selectionAnimationEasing": { "type": "string" },
            "caretWidth": { "type": "number", "minimum": 0.5, "maximum": 12 },
            "caretCornerRadius": { "type": "number", "minimum": 0, "maximum": 12 },
            "caretMinHeight": { "type": "number", "minimum": 8, "maximum": 240 },
            "caretAnimationDurationMilliseconds": { "type": "integer", "minimum": 0, "maximum": 5000 },
            "caretBlinkMilliseconds": { "type": "integer", "minimum": 100, "maximum": 10000 },
            "caretTypingBlinkPauseMilliseconds": { "type": "integer", "minimum": 0, "maximum": 10000 },
            "caretAnimationEasing": { "type": "string" },
            "statusFontSize": { "type": "number", "minimum": 8, "maximum": 72 },
            "statusTitleFontSize": { "type": "number", "minimum": 8, "maximum": 72 },
            "statusPanelPadding": { "type": "number", "minimum": 0, "maximum": 96 },
            "statusPanelSpacing": { "type": "number", "minimum": 0, "maximum": 48 },
            "statusHintOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "loadingIndicatorHeight": { "type": "number", "minimum": 0, "maximum": 24 },
            "foregroundOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "mutedForegroundOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "borderOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "searchBackgroundOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "searchBorderOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "separatorOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "iconOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "iconBackgroundOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "iconBorderOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "backgroundImagePath": { "type": "string" },
            "backgroundImageOpacity": { "type": "number", "minimum": 0, "maximum": 1 },
            "backgroundImageStretch": { "type": "string", "enum": ["None", "Fill", "Uniform", "UniformToFill"] },
            "background": { "$ref": "#/$defs/themeValue" },
            "foreground": { "$ref": "#/$defs/themeValue" },
            "mutedForeground": { "$ref": "#/$defs/themeValue" },
            "accent": { "$ref": "#/$defs/themeValue" },
            "selectedBackground": { "$ref": "#/$defs/themeValue" },
            "border": { "$ref": "#/$defs/themeValue" },
            "resources": {
              "type": "object",
              "description": "Extra WPF resource overrides. Values may be colors, numbers, or strings.",
              "additionalProperties": { "$ref": "#/$defs/themeValue" }
            }
          },
          "$defs": {
            "themeValue": {
              "type": "string"
            }
          }
        }
        """;
}
